#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';
require __DIR__ . '/app/Config/environment.php';

use Symfony\Component\Console\Application;

use App\Console\Commands\TestCommand;
use App\Console\Commands\ServeCommand;
use App\Console\Commands\MigrateCommand;
use App\Console\Commands\MakeModelCommand;
use App\Console\Commands\MakeGrammarCommand;
use App\Console\Commands\MakeMigrationCommand;
use App\Console\Commands\MakeMiddlewareCommand;
use App\Console\Commands\MakeControllerCommand;

$application = new Application();
$application->setVersion('1.0');

# add our commands
$application->add(new TestCommand());
$application->add(new ServeCommand());
$application->add(new MigrateCommand());
$application->add(new MakeModelCommand());
$application->add(new MakeGrammarCommand());
$application->add(new MakeMigrationCommand());
$application->add(new MakeMiddlewareCommand());
$application->add(new MakeControllerCommand());

$application->run();