#!/usr/bin/env php
<?php

define('MODULUS_START', microtime(true));

use App\Console\Kernel;
use Modulus\Framework\Upstart;

require __DIR__. '/vendor/autoload.php';

(new Upstart)->boot(true);

$application = Kernel::console();
$application->run();