#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

use Symfony\Component\Console\Application;

$application = new Application();
$application->setVersion('1.0');

# add our commands
$application->add(new TestCommand());
$application->add(new ServeCommand());

$application->run();